### ISSUE TITLE
tiler only partially writing tiles

### ISSUE THREAD

**Issue by jebyrnes** [leonawicz/tiler#13]
OK, here's a new take - 

Using the current branch (so, system stderr is being returned), I'm working with https://www.dropbox.com/s/3bhry7hwhyo0vrf/merged_falkands_leaflet.tif?dl=0 - when I attempt to tile it 0-7, starting at different points depending on the runs, I don't get complete output to directories. E.g., 0 is complete, 1 is complete, but if I look at, say, 6, it might only have 21 and 22 - not 0-22.

Not sure why this is so.....

I'm reluctant to loop over and run each zoom level separately, only as I'm doing this with a raster that's projected for leaflet, and the first thing that happens each time I run `tile` is that the raster is reprojected, which takes time, but, well, thoughts?

**Comment by leonawicz** [comment]
I'm still saddled with everything but `tiler` but at the moment one thing I can think that may lessen the troubleshooting burden for you on this is to do all your reprojection up front as prep before using `tile`. If `tile` does not need to do any reprojection, the data goes right to python. If `tile` needs to reproject first, then it's going to load it all into memory in R, do the reprojection, save that new raster to disk in a temp directory, and then tell python to use that file (and then it's cleaned up afterward).

I think I have a mention of this somewhere but I can't recall where at the moment. Maybe in the docs, maybe in another issue. But if you can prep the data first so no reprojection is needed, you might save a ton of time.

**Comment by jebyrnes** [comment]
No worries - I have the data projected to the leaflet projection (as figured out in https://github.com/ropensci/tiler/issues/10) - however, a) tile insists on reprojecting again - not sure to what - maybe 4326? - but...then the lineup does indeed work. It's the oddest thing.

**Comment by leonawicz** [comment]
Closing since this issue is very old.
