### ISSUE TITLE
try to automatically detect python path

### ISSUE THREAD

**Issue by achubaty** [leonawicz/tiler#19]
It would be great if out-of-the-box `tiler` would attempt to find the correct python version, rather than leaving it to the user to ensure it's set.

I know it gets complicated (especially on Windows) but I think the following check is simple enough to be set as the default option in lieu of the current `"python"`, and has worked well for me on macOS (with brew install of spatial libraries), Windows (with OSgeo4W), and Ubuntu 20.04+:

```r
  pythonPath <- if (nzchar(Sys.which("python3"))) {
    Sys.which("python3")
  } else if (nzchar(Sys.which("python"))) {
    Sys.which("python")
  } else {
    "python" ## use as is, but tests will likely fail
  }
  tiler_options(python = pythonPath)
```

sidenote: this came about as a response to #16

**Comment by leonawicz** [comment]
Hi, I agree that would be ideal. Is this what you have in mind for `zzz.R`?

```
.onLoad <- function(lib, pkg){
  python_path <- if (nzchar(Sys.which("python3"))) {
    Sys.which("python3")
  } else if (nzchar(Sys.which("python"))) {
    Sys.which("python")
  } else {
    "python"
  }

  .tiler_env$opts <- list(python = python_path, osgeo4w = "")

  if(.Platform$OS.type == "windows"){
    tiler_options(osgeo4w = "OSGeo4W.bat")
  }
}
```

**Comment by achubaty** [comment]
Yes, putting it in `.onload` where those tiler options are set would be ideal
