### ISSUE TITLE
python syntax errors

### ISSUE THREAD

**Issue by achubaty** [leonawicz/tiler#20]
I see the following when running the tests in `test-tile.R`:

```r
  File "inst/python/gdal2tilesIMG.py", line 800
  print 'Cache: %s MB' % (gdal.GetCacheMax() / 1024 / 1024)
  ^
    SyntaxError: invalid syntax
```

It doesn't trigger an error in R - tiler chugs along and the tests pass, but this needs to be resolved.

**Comment by leonawicz** [comment]
Fixed.
