### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [leonawicz/tiler#22]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

Removing retiring packages from DESCRIPTION, and running CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path gives this log:
[00check.log](https://github.com/ropensci/tiler/files/11364868/00check.log)

**Comment by rsbivand** [comment]
@leonawicz See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN; you were first warned more than six months ago.

**Comment by leonawicz** [comment]
Note: rgdal has been removed on GitHub master branch.

**Comment by rsbivand** [comment]
Thanks. You may need terra too in Suggests: for CRAN extra checks when only listed suggested packages are available, as raster has a strong dependence on terra.

**Comment by rsbivand** [comment]
Status as is should be OK, my check log: 
[00check.log](https://github.com/ropensci/tiler/files/12061809/00check.log)

**Comment by leonawicz** [comment]
Thank you

**Comment by leonawicz** [comment]
CRAN submission is offline until August 7. I will submit a new release afterward. I believe everything is good to go.
