### ISSUE TITLE
Python-gdal on Travis and Appveyor

### ISSUE THREAD

**Issue by leonawicz** [leonawicz/tiler#6]
GDAL remains unavailable on Travis and Appveyor. While tests and examples using `tile` can run without creating tiles, tests and examples will fail if they require access to outputs of `tile`, as they will not exist. I have not yet figured out how to make the required libraries and bindings available in Travis and Appveyor via `.travis.yml` and `appveyor.yml`. Help appreciated.

**Comment by achubaty** [comment]
are you interested in using GitHub Actions instead? I can help with setting this up

**Comment by leonawicz** [comment]
> are you interested in using GitHub Actions instead? I can help with setting this up

Hi, yes this is an old one. Travis is not even a good option anymore. GitHub Actions would be ideal. Along with any PR for your other requested improvements, I would be happy to add you to the package as a contributor. My time is limited lately but I can make time to review changes.

Regards

**Comment by achubaty** [comment]
a few tweaks later and i have basic checks running:

- R CMD check on macOS (R release) and ubuntu 20.04 (R-devel, R release, R oldrel)
- codecov coverage check running on ubuntu-latest

see https://github.com/achubaty/tiler/actions
